name: Tuist Cache

on:
  push:
    branches:
      - main
      - testing_library_change
  pull_request:

jobs:
  tuist-cache:
    name: Run Tuist Cache
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH  # For Apple Silicon
          eval "$(/opt/homebrew/bin/brew shellenv)" || eval "$(/usr/local/bin/brew shellenv)"

      - name: Tap Tuist repository and install Tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Verify Tuist Installation
        run: tuist

      - name: Tuist cache
        run: |
          export TUIST_CONFIG_TOKEN=tuist_0194cb73-0f3a-7067-ae79-231176a07076_h8hM/0vdGWCeJGdlPobpPYkCEx8=

          echo $CI
          echo "INSTALL"
          tuist install
          echo "GENERATE"
          tuist generate
          echo "BUILD 2"
          tuist build TestingTuist
