name: Tuist Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tuist-cache:
    name: Run Tuist Cache
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Homebrew
        run: |
          /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          echo "/opt/homebrew/bin" >> $GITHUB_PATH  # For Apple Silicon
          eval "$(/opt/homebrew/bin/brew shellenv)" || eval "$(/usr/local/bin/brew shellenv)"

      - name: Tap Tuist repository and install Tuist
        run: |
          brew tap tuist/tuist
          brew install --formula tuist

      - name: Verify Tuist Installation
        run: tuist

      - name: Tuist cache
        run: |
          echo $TUIST_CONFIG_TOKEN
          echo $CI
          tuist install
          tuist cache
        env:
          TUIST_CONFIG_TOKEN: 0194cb16-4d3a-7fba-8b6e-a67ab0eeef92
