name: Tuist Cache

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  tuist-cache:
    name: Run Tuist Cache
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Mise
        run: |
          curl -fsSL https://mise.run | sh
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          eval "$(mise activate bash)"

      - name: Install Tuist using Mise
        run: |
          mise install tuist
          echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH

      - name: Verify Tuist Installation
        run: tuist --version

      - name: Set Tuist Token
        run: echo "TUIST_CONFIG_TOKEN=0194cb15-5644-7024-99d6-37fb733ae939" >> $GITHUB_ENV

      - name: Warm Tuist Cache
        run: tuist cache
